### ISSUE TITLE
Failed to run the container 

### ISSUE THREAD

**Issue by swiftdiaries** [afritzler/docker-tensorflow-keras-gpu#1]
$ kubectl exec -it tensorflow-keras-gpu -- /bin/bash
Error from server (BadRequest): pod tensorflow-keras-gpu does not have a host assigned

Hey,

I tried running the container in kubernetes and I got the above problem, is there any way I can solve this issue?

**Comment by afritzler** [comment]
Was the pod actually scheduled? What is `kubectl get pods -n MY_NAMESPACE` returning?

Running `kubectl create -f example-pod.yaml -n MY_NAMESPACE` followed by `kubectl get pods -n MY_NAMESPACE` should return something like this:
```
NAME                   READY     STATUS    RESTARTS   AGE
tensorflow-keras-gpu   1/1       Running   0          3m
```

Once the state is running, you should be able to attach a bash session to it:
```
kubectl -n MY_NAMESPACE exec -it tensorflow-keras-gpu -- /bin/bash
```

Also make sure that you labeled your GPU node with 
```
kubectl label node <NODE_NAME> gpu="true"
```
since this is the key the `NodeSelector` is looking for.

**Comment by swiftdiaries** [comment]
The pod wasn't scheduled. The GPU's weren't discoverable. Turns out the driver location is different on my node and had to modify the YAML file and mount the appropriate paths. Thank you so much for your help. Your project really helped me understand a lot of things.
